// <auto-generated />
namespace JC_Family.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JC_Family_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JC_Family_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201806120721387_JC_Family_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
